"""initial schema

Revision ID: a715aad34b31
Revises: 
Create Date: 2026-09-17 14:24:04.410472

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a715aad34b31'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_ref', sa.String(length=160), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_entry_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entry_actor'), ['actor'], unique=False)

    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('storage_state_path', sa.Text(), nullable=True),
    sa.Column('user_data_dir', sa.Text(), nullable=True),
    sa.Column('totp_secret_ref', sa.String(length=80), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('proxy_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('vendor', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('entries', sa.JSON(), nullable=False),
    sa.Column('rotation', sa.String(length=24), nullable=False),
    sa.Column('sticky_ttl_s', sa.Integer(), nullable=False),
    sa.Column('username_template', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('gb_used', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scraper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('yaml_path', sa.Text(), nullable=False),
    sa.Column('schedule', sa.String(length=80), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('promotion_policy', sa.String(length=20), nullable=False),
    sa.Column('fallback_enabled', sa.Boolean(), nullable=False),
    sa.Column('fallback_model', sa.String(length=60), nullable=True),
    sa.Column('budget_usd_month', sa.Float(), nullable=False),
    sa.Column('proxy_pool', sa.String(length=80), nullable=True),
    sa.Column('profile', sa.String(length=80), nullable=True),
    sa.Column('respect_robots', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('acknowledged_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ack_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scraper', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scraper_name'), ['name'], unique=True)

    op.create_table('secret',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value_enc', sa.LargeBinary(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('delivery_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraper_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('fmt', sa.String(length=24), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('only_on_failure', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scraper_id'], ['scraper.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraper_id', sa.Integer(), nullable=False),
    sa.Column('script_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('engine_used', sa.String(length=40), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('proxy_used', sa.String(length=120), nullable=True),
    sa.Column('block_reason', sa.String(length=60), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('validator_report', sa.JSON(), nullable=True),
    sa.Column('log_path', sa.Text(), nullable=True),
    sa.Column('artifact_dir', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scraper_id'], ['scraper.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index(
            'ix_run_scraper_created',
            ['scraper_id', sa.literal_column('created_at DESC')],
            unique=False,
        )
        batch_op.create_index(batch_op.f('ix_run_scraper_id'), ['scraper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_status'), ['status'], unique=False)

    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_sent', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['delivery_target.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_status'), ['status'], unique=False)

    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraper_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('agent', sa.String(length=24), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scraper_id'], ['scraper.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_agent'), ['agent'], unique=False)

    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('scraper_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scraper_id'], ['scraper.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_record_row_hash'), ['row_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_scraper_id'), ['scraper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_source'), ['source'], unique=False)

    op.create_table('repair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraper_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('candidate_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('is_minor', sa.Boolean(), nullable=False),
    sa.Column('test_run_id', sa.Integer(), nullable=True),
    sa.Column('transcript_path', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=40), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['scraper_id'], ['scraper.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repair', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repair_scraper_id'), ['scraper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repair_status'), ['status'], unique=False)

    op.create_table('run_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=120), nullable=False),
    sa.Column('null_rate', sa.Float(), nullable=False),
    sa.Column('distinct_count', sa.Integer(), nullable=False),
    sa.Column('sample', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_metric', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_metric_run_id'), ['run_id'], unique=False)

    op.create_table('script_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraper_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('yaml', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_minor', sa.Boolean(), nullable=False),
    sa.Column('has_custom_python', sa.Boolean(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('test_run_id', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.String(length=40), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scraper_id'], ['scraper.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scraper_id', 'version')
    )
    with op.batch_alter_table('script_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_script_version_scraper_id'), ['scraper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_script_version_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('script_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_script_version_status'))
        batch_op.drop_index(batch_op.f('ix_script_version_scraper_id'))

    op.drop_table('script_version')
    with op.batch_alter_table('run_metric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_metric_run_id'))

    op.drop_table('run_metric')
    with op.batch_alter_table('repair', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repair_status'))
        batch_op.drop_index(batch_op.f('ix_repair_scraper_id'))

    op.drop_table('repair')
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_record_source'))
        batch_op.drop_index(batch_op.f('ix_record_scraper_id'))
        batch_op.drop_index(batch_op.f('ix_record_run_id'))
        batch_op.drop_index(batch_op.f('ix_record_row_hash'))

    op.drop_table('record')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_agent'))

    op.drop_table('llm_usage')
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_status'))
        batch_op.drop_index(batch_op.f('ix_delivery_run_id'))

    op.drop_table('delivery')
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_status'))
        batch_op.drop_index(batch_op.f('ix_run_scraper_id'))
        batch_op.drop_index('ix_run_scraper_created')

    op.drop_table('run')
    op.drop_table('delivery_target')
    op.drop_table('secret')
    with op.batch_alter_table('scraper', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scraper_name'))

    op.drop_table('scraper')
    op.drop_table('proxy_pool')
    op.drop_table('profile')
    with op.batch_alter_table('audit_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_entry_actor'))
        batch_op.drop_index(batch_op.f('ix_audit_entry_action'))

    op.drop_table('audit_entry')
    # ### end Alembic commands ###
